//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GisDataBase : DbContext
    {
        public GisDataBase()
            : base("name=GisDataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company> Companies { get; set; }
        public DbSet<FuelType> FuelTypes { get; set; }
        public DbSet<Land> Lands { get; set; }
        public DbSet<OwnershipType> OwnershipTypes { get; set; }
        public DbSet<Person> Persons { get; set; }
        public DbSet<Price> Prices { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<Spec> Specs { get; set; }
        public DbSet<Station> Stations { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
