//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land
    {
        public int ID { get; set; }
        public int Station_ID { get; set; }
        public int OwnerShipType_ID { get; set; }
        public int Owner_ID { get; set; }
        public string Description { get; set; }
    
        public virtual OwnershipType OwnershipType { get; set; }
        public virtual Person Person { get; set; }
        public virtual Station Station { get; set; }
    }
}
