//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Station_ID { get; set; }
        public int Fuel_ID { get; set; }
        public double Price1 { get; set; }
    
        public virtual FuelType FuelType { get; set; }
        public virtual Station Station { get; set; }
    }
}
